package com.github.ucov.models;

public enum SymbolUse {
    SYMBOL_USE_INSTANTIATION, // TYPE_USE, CLASS_USE
    SYMBOL_USE_TYPE_REFERENCE, // TYPE_USE
    SYMBOL_USE_INHERITANCE, // CLASS_USE
    SYMBOL_USE_IMPLEMENTATION, // INTERFACE_USE
    SYMBOL_USE_EXTENSION, // INTERFACE_USE
    SYMBOL_USE_INVOCATION, // METHOD_USE
    SYMBOL_USE_STATIC_INVOCATION, // METHOD_USE
    SYMBOL_USE_OVERRIDING, // METHOD_USE
    SYMBOL_USE_INSTANCE_FIELD_READ, // FIELD_USE
    SYMBOL_USE_INSTANCE_FIELD_WRITE, // FIELD_USE,
    SYMBOL_USE_VIRTUAL_INVOCATION
}
